---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  #- name: ubuntu-12.04
  #- name: ubuntu-12.10
  #- name: ubuntu-13.04
  - name: ubuntu-13.10

suites:
  - name: default
    run_list:
      - recipe[chef-continuum-anaconda::default]
    attributes:
