# https://github.com/sethvargo/chefspec#reporting
require 'chefspec'
ChefSpec::Coverage.start! do
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # Specify the Chef log_level (default: :warn)
  #config.log_level = :debug

  # Specify the path to a local JSON file with Ohai data (default: nil)
  #config.path = 'ohai.json'

  # Specify the operating platform to mock Ohai data from (default: nil)
  #config.platform = 'ubuntu'
  # Specify the operating version to mock Ohai data from (default: nil)
  #config.version = '12.04'
end
